### ISSUE TITLE
when viewpage inside recycle,   java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by captain-miao** [hrskrs/InstaDotView#3]
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.hrskrs.instadotlib.InstaDotView.setupNormalDots(InstaDotView.java:319)
        at com.hrskrs.instadotlib.InstaDotView.updateDots(InstaDotView.java:293)
        at com.hrskrs.instadotlib.InstaDotView.onPageChange(InstaDotView.java:284)

**Comment by mformetal** [comment]
I believe this is happening due to the `previousPage` var not being reset correctly. It's reset in `onPageChange`, but only after trying to use its previous value to index a list. This is currently causing a crash; is there any way you can get a fix out?

**Comment by captain-miao** [comment]
yeah, dot size and dot view is not update in the same time. 

I try to fixed it, but fail 😭.

**Comment by shrastiRisor** [comment]
for those who are still facing the issue: fix is https://github.com/hrskrs/InstaDotView/pull/6
